// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTab: typeof import('./src/components/Base/BaseTab.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTable: typeof import('./src/components/ScrollTable.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }

}
